"""add tenant tier

Revision ID: 6b3457f1ab86
Revises: bb63e6ac5b76
Create Date: 2026-02-04 14:42:50.451485

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '6b3457f1ab86'
down_revision = 'bb63e6ac5b76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tier', sa.String(length=50), nullable=False, server_default='free'))
    op.add_column('tenants', sa.Column('token_limit_per_day', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('spend_limit_per_day_usd', sa.Float(), nullable=True))
    op.alter_column('tenants', 'tier', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'spend_limit_per_day_usd')
    op.drop_column('tenants', 'token_limit_per_day')
    op.drop_column('tenants', 'tier')
    # ### end Alembic commands ###
